apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiacoes-deployment
  labels:
    app: apiacoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiacoes
  template:
    metadata:
      labels:
        app: apiacoes
    spec:
      containers:
      - name: apiacoes
        image: renatogroffe/apiacoes-kafka-dotnet5:latest
        env:
          - name: ApplicationInsights__InstrumentationKey
            valueFrom:
                secretKeyRef:
                  name: apiacoes-secrets
                  key: AppInsightsAPIAcoes
          - name: ConnectionStrings__AppConfiguration
            valueFrom:
                secretKeyRef:
                  name: apiacoes-secrets
                  key: AppConfiguration
        ports:
        - containerPort: 80